### ISSUE TITLE
an issue installing amply in python 3.3

### ISSUE THREAD

**Issue by pchtsp** [willu47/amply#3]
Hello again!

The Travis CI is giving an error on this specific python version for pulp. And from what I can see, it happens when installing amply. Can you see anything weird? (I have no idea what it means).

https://travis-ci.org/github/coin-or/pulp/jobs/700789057

For some reason it complains about a:

```    
pkg_resources.DistributionNotFound: The 'setuptools-scm' distribution was not found and is required by the application
```

**Comment by willu47** [comment]
The latest version of the dependency `setuptools-scm` does not support Python 3.3.  Note Python 3.3 is no longer actively developed, and is designated ['end of life'](https://devguide.python.org/#status-of-python-branches).

Unfortunately, I cannot easily test this as I cannot even install Python 3.3 using my current CI setup using miniconda!

**Comment by pchtsp** [comment]
Hello Will,
We have just taken out support for python 3.3 in pulp to integrate with amply so no need on fixing it here.

Thanks anyway!

F.
